### ISSUE TITLE
rejects yaml null '~'

### ISSUE THREAD

**Issue by jurgenweber** [garethr/kubetest#16]
```
{
  "level": "fatal",
  "msg": "type <nil> is not a supported skylark type",
  "time": "2018-01-17T12:12:51+11:00"
}
```

```
     env:
        - name: PHP_SESSION_SAVE_HANDLER
          value: ~
        - name: PHP_SESSION_SERIALIZE_HANDLER
          value: ~
```

It is value YAML: http://yaml.org/type/null.html

best way to handle this?
