### ISSUE TITLE
Can not parse YAMLs with anchors

### ISSUE THREAD

**Issue by estahn** [garethr/kubetest#29]
Example:
```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  ...
  labels: &labels
    app: foobar
    environment: qa
    ...
spec:
  template:
    metadata:
      labels:
        <<: *labels
    spec:
      ...
```
